### ISSUE TITLE
Blank screen when using google auth

### ISSUE THREAD

**Issue by hodeyp** [ionic-team/ionic-contrib-firebase-login#1]
Thanks so much for putting this seed together, has really accelerated my initial exploration into using ionic to build an iOS version of a web app I have built for a client.

I do, however, have a problem. I use google authentication for firebase and when running the ionic app in the browser (using ionic serve) it shows the login popup and on authentication redirects to the homepage. However when I try this on the iPhone emulator or on an actual iOS device it jut displays a blank screen. 

Can you confirm the seed you have kindly deployed works on iOS emulator when you run it?

**Comment by nicfo** [comment]
Have you found a solution yet? I'm having the same problem.
It let's me log in with the google account but then leads to a blank page.

**Comment by Ionitron** [comment]
Greetings @hodeyp!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.

**Comment by xiaofanwu** [comment]
I have the same problem when running command ionic run android instead of running in Ionic Viewer？Anyway can help?
