### ISSUE TITLE
Can I demo this app?

### ISSUE THREAD

**Issue by davidpatrick** [ionic-team/ionic-contrib-firebase-login#2]
I cloned the repo and ran 'ionic serve' which popped up a web browser running this app.  I try and create an account and login, but with no success.  The create account button doesn't do anything, no console errors, and the facebook integration pops up a blank window.  I've tried replacing the app.js references to firebaseio to my own firebase account, but still nothing.  What am I missing?

**Comment by Ionitron** [comment]
Greetings @davidpatrick!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
