### ISSUE TITLE
Blank screen when go to create account

### ISSUE THREAD

**Issue by sivaramsi** [ionic-team/ionic-contrib-firebase-login#3]
I just build the app for android platform and tried in emulator and i installed in my phone as well ...when i try to click create an account in the app it navigates to blank white screen ..

**Comment by Ionitron** [comment]
Greetings @sivaramsi!

I've closed this issue because my sensors indicated it was old and inactive, and may have already been fixed in recent versions of Ionic. However, if you are still experiencing this issue, please feel free to reopen this issue by creating a new one, and include any examples and other necessary information, so that we can look into it further.

Thank you for allowing me to assist you.
